### ISSUE TITLE
Dataset used

### ISSUE THREAD

**Issue by mtttmyz** [mikgroup/espirit-python#1]
Hi sidward, 

I am a student who is just starting to study this area, and I found your code very useful. As I reproduce your work, I would like to know what data you selected from the website mridata.org? Because I would like to download it and explore it myself. And why does the data preprocessing in clf.py deal with HDR and clf files? Thank you for your time.

**Comment by sidward** [comment]
Hi!

1. I don't remember which exact dataset the knee data in the `data` folder was, sorry. As you mentioned, you can get raw data from mridata.org.
2. cfl/hdr is the data format used by [BART](https://mrirecon.github.io/bart/). `cfl.py` just loads in this data as a numpy array.
